### ISSUE TITLE
FileNotFoundException on startup

### ISSUE THREAD

**Issue by skuehlshelby** [AvaloniaUtils/HyperText.Avalonia#2]
Hello!

This control looks super handy, but I just added it to my project and now receive the following exception on startup:

System.IO.FileNotFoundException: 'Could not load file or assembly 'Avalonia.Input, Version=0.10.15.0, Culture=neutral, PublicKeyToken=c8d484a7012f9a8b'. The system cannot find the file specified.'

I removed your package, and everything works as normal again.

Again, seems really nice, would love to use this in the future.

I am using Avalonia 11.0.3.

**Comment by Mohammed85-dev** [comment]
I am getting the same problem

**Comment by XDgl233** [comment]
It seems the Nuget release is not updated to Avalonia 11. But you can still manually add the project in this repo, it supports rc1.

**Comment by CreateLab** [comment]
Check actual version, fix this
